name: Build Celcat ICS

on:
  workflow_dispatch: {}          # bouton "Run workflow"
  schedule:
    - cron: "0 3 * * *"          # tous les jours ~05:00 Paris

permissions:
  contents: write                # pour git push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (before)
        run: |
          pwd
          ls -la
          ls -la docs || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pin aiohttp 3.8.x)
        run: |
          python -m pip install --upgrade pip
          # Aiohttp 3.8.6 (évite le bug de timeout des versions 3.9+)
          pip install "aiohttp==3.8.6"
          # Installer celcat-scraper SANS dépendances pour garder aiohttp 3.8.6
          pip install --no-deps "celcat-scraper==1.1.3"
          # Le reste
          pip install "icalendar==5.0.12" "pytz==2024.1"
          python - << 'PY'
import aiohttp
print("aiohttp version:", aiohttp.__version__)
PY

      - name: Generate ICS
        env:
          CELCAT_USERNAME: ${{ secrets.CELCAT_USERNAME }}
          CELCAT_PASSWORD: ${{ secrets.CELCAT_PASSWORD }}
        run: |
          mkdir -p docs
          python generate_ics.py
          echo "----- docs content -----"
          ls -la docs

      - name: Commit ICS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/edt.ics
          git commit -m "Update ICS" || echo "No changes to commit"
          git push
