      - name: Install deps (pin aiohttp 3.8.x)
        run: |
          python -m pip install --upgrade pip
          # 1) Installer aiohttp 3.8.6 et NE PAS laisser celcat-scraper le ré-upgrader
          pip install "aiohttp==3.8.6"
          # 2) Installer celcat-scraper SANS dépendances (pour garder aiohttp 3.8.6)
          pip install --no-deps "celcat-scraper==1.1.3"
          # 3) Le reste
          pip install "icalendar==5.0.12" "pytz==2024.1"
          # 4) Sanity check
          python - << 'PY'
import aiohttp, sys
print("aiohttp version:", aiohttp.__version__)
try:
    import celcat_scraper
    print("celcat-scraper:", getattr(celcat_scraper, "__version__", "unknown"))
except Exception as e:
    print("celcat-scraper import failed:", e, file=sys.stderr)
PY
