name: Build Celcat ICS

on:
  schedule:
    - cron: "0 3 * * *"   # tous les jours à 03:00 UTC ≈ 05:00 à Paris
  workflow_dispatch: {}    # bouton "Run workflow" manuel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate ICS
        env:
          CELCAT_USERNAME: ${{ secrets.CELCAT_USERNAME }}
          CELCAT_PASSWORD: ${{ secrets.CELCAT_PASSWORD }}
        run: |
          python generate_ics.py

      - name: Commit ICS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/edt.ics
          git commit -m "Update ICS" || echo "No changes"
          git push
